version: '3.8'
services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - .:/app
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - MAX_WORKERS=2
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
